
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 24 12:39:58 CET 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FROM = 14;
  public static final int QUESTION = 2;
  public static final int EQUAL = 3;
  public static final int ENCODING = 21;
  public static final int RUNG = 10;
  public static final int XML = 7;
  public static final int CONTACT = 13;
  public static final int PROGRAM = 8;
  public static final int NUM = 19;
  public static final int TYPE = 18;
  public static final int EOF = 0;
  public static final int DIV = 4;
  public static final int error = 1;
  public static final int PORT = 16;
  public static final int MIN = 5;
  public static final int VERSION = 20;
  public static final int MAX = 6;
  public static final int FOR = 9;
  public static final int COIL = 17;
  public static final int TO = 15;
  public static final int SECTION2 = 12;
  public static final int SECTION1 = 11;
}

